const cardData = [
    {
      id: 1,
      label: "Hot Update",
      title: "Introducing routing forms",
      subTitle: "Screen and Quality people before they book with you",
      readTime: "Read time: 6 Minutes",
      description: "Ask site Visitors questions to automatically present scheduling options based on their answers",
    },
    {
      id: 2,
      label: "Latest Enhancement",
      title: "New Feature Alert",
      subTitle: "Enhanced User Profiles",
      readTime: "Read time: 5 Minutes",
      description: "Create detailed user profiles to understand and cater to your audience better.",
    },
    {
      id: 3,
      label: "Upgrade Alert",
      title: "Improvements to Calendar Sync",
      subTitle: "Seamless Integration Across Platforms",
      readTime: "Read time: 4 Minutes",
      description: "Sync your calendar effortlessly with popular platforms for better time management.",
    },
    {
      id: 4,
      label: "Feature Highlight",
      title: "Enhanced Security Measures",
      subTitle: "Protecting Your Data",
      readTime: "Read time: 7 Minutes",
      description: "We've upgraded our security protocols to ensure your data remains safe and confidential.",
    },
    {
      id: 5,
      label: "New Arrival",
      title: "New Payment Options",
      subTitle: "More Ways to Pay",
      readTime: "Read time: 3 Minutes",
      description: "Introducing multiple payment options for your convenience and flexibility.",
    },
    {
      id: 6,
      label: "Fresh Release",
      title: "Improved Mobile Experience",
      subTitle: "Optimized for Mobile Users",
      readTime: "Read time: 5 Minutes",
      description: "Enjoy a smoother and more responsive experience on our mobile platform.",
    },
    {
      id: 7,
      label: "What's New",
      title: "Introducing Analytics Dashboard",
      subTitle: "Track Your Performance",
      readTime: "Read time: 8 Minutes",
      description: "Gain insights into your performance with our new analytics dashboard.",
    },
    {
      id: 8,
      label: "Improved Functionality",
      title: "New Customization Options",
      subTitle: "Make It Your Own",
      readTime: "Read time: 4 Minutes",
      description: "Personalize your experience with new customization options tailored to your preferences.",
    },
    {
      id: 9,
      label: "Recent Addition",
      title: "Improved Customer Support",
      subTitle: "We're Here to Help",
      readTime: "Read time: 5 Minutes",
      description: "Our dedicated support team is available 24/7 to assist you with any queries or issues.",
    },
    {
      id: 10,
      label: "Exciting Update",
      title: "Advanced Search Features",
      subTitle: "Find What You're Looking For",
      readTime: "Read time: 5 Minutes",
      description: "Discover enhanced search capabilities to quickly locate the information you need.",
    },
    {
      id: 11,
      label: "New Feature",
      title: "Collaborative Workspace",
      subTitle: "Work Together Seamlessly",
      readTime: "Read time: 6 Minutes",
      description: "Collaborate with your team more efficiently with our new collaborative workspace feature.",
    },
    {
      id: 12,
      label: "Upgrade Alert",
      title: "Enhanced File Sharing",
      subTitle: "Share Files Easily",
      readTime: "Read time: 4 Minutes",
      description: "Experience faster and more reliable file sharing with our upgraded file sharing feature.",
    },
    {
      id: 13,
      label: "Feature Highlight",
      title: "Improved Notifications",
      subTitle: "Stay Informed",
      readTime: "Read time: 3 Minutes",
      description: "Receive timely and relevant notifications to stay updated on important events and activities.",
    },
    {
      id: 14,
      label: "What's New",
      title: "Custom Themes",
      subTitle: "Personalize Your Experience",
      readTime: "Read time: 5 Minutes",
      description: "Choose from a variety of custom themes to personalize your user interface.",
    },
    {
      id: 15,
      label: "Latest Enhancement",
      title: "Enhanced User Onboarding",
      subTitle: "Get Started Easily",
      readTime: "Read time: 6 Minutes",
      description: "Experience a smoother and more intuitive user onboarding process with our latest enhancements.",
    },
    {
      id: 16,
      label: "Hot Update",
      title: "Improved Performance",
      subTitle: "Faster and More Responsive",
      readTime: "Read time: 5 Minutes",
      description: "Enjoy faster and more responsive performance across all devices with our latest update.",
    },
    {
      id: 17,
      label: "New Arrival",
      title: "Advanced Analytics Tools",
      subTitle: "Deep Insights",
      readTime: "Read time: 7 Minutes",
      description: "Gain deeper insights into your data with our advanced analytics tools and features.",
    },
    {
      id: 18,
      label: "Fresh Release",
      title: "Enhanced Collaboration Features",
      subTitle: "Work Together Anywhere",
      readTime: "Read time: 6 Minutes",
      description: "Collaborate with your team effectively from anywhere with our enhanced collaboration features.",
    },
    {
        id: 19,
        label: "Feature Update",
        title: "Enhanced Security Measures",
        subTitle: "Data Protection",
        readTime: "Read time: 7 Minutes",
        description: "We've implemented advanced security features to protect your data and privacy.",
      },
      {
        id: 20,
        label: "New Feature",
        title: "Voice Search",
        subTitle: "Search Hands-Free",
        readTime: "Read time: 4 Minutes",
        description: "Introducing voice search functionality for a more convenient and accessible search experience.",
      },
      {
        id: 21,
        label: "Upgrade Alert",
        title: "Improved User Interface",
        subTitle: "Sleek and Modern Design",
        readTime: "Read time: 5 Minutes",
        description: "Experience our new sleek and modern user interface designed for enhanced usability.",
      },
      {
        id: 22,
        label: "Latest Enhancement",
        title: "Multi-Language Support",
        subTitle: "Speak Your Language",
        readTime: "Read time: 6 Minutes",
        description: "We now support multiple languages to cater to our diverse user base.",
      },
      {
        id: 23,
        label: "Hot Update",
        title: "Quick Access Toolbar",
        subTitle: "Easy Access to Features",
        readTime: "Read time: 3 Minutes",
        description: "Introducing a quick access toolbar for easy access to your favorite features.",
      },
      {
        id: 24,
        label: "New Arrival",
        title: "Dark Mode",
        subTitle: "Easier on the Eyes",
        readTime: "Read time: 4 Minutes",
        description: "Switch to dark mode for a more comfortable viewing experience, especially in low-light conditions.",
      },
      {
        id: 25,
        label: "Feature Highlight",
        title: "Offline Access",
        subTitle: "Work Without Internet",
        readTime: "Read time: 5 Minutes",
        description: "Access your important data and documents even without an internet connection with our new offline access feature.",
      },
      {
        id: 26,
        label: "What's New",
        title: "Document Versioning",
        subTitle: "Keep Track of Changes",
        readTime: "Read time: 6 Minutes",
        description: "Keep track of changes and revisions with our new document versioning feature.",
      },
      {
        id: 27,
        label: "Improved Functionality",
        title: "Advanced Filters",
        subTitle: "Find What You Need",
        readTime: "Read time: 5 Minutes",
        description: "Use advanced filters to quickly find the information or data you need.",
      },
      {
        id: 28,
        label: "Recent Addition",
        title: "Task Management",
        subTitle: "Organize Your Tasks",
        readTime: "Read time: 4 Minutes",
        description: "Manage and organize your tasks more efficiently with our new task management feature.",
      },
      {
        id: 29,
        label: "Exciting Update",
        title: "Customizable Dashboard",
        subTitle: "Personalize Your Dashboard",
        readTime: "Read time: 7 Minutes",
        description: "Customize your dashboard to display the information and data that matters most to you.",
      },
      {
        id: 30,
        label: "New Feature",
        title: "Real-time Collaboration",
        subTitle: "Collaborate Instantly",
        readTime: "Read time: 5 Minutes",
        description: "Collaborate with your team in real-time with our new real-time collaboration feature.",
      },
      {
        id: 31,
        label: "Upgrade Alert",
        title: "Enhanced File Management",
        subTitle: "Organize Your Files",
        readTime: "Read time: 6 Minutes",
        description: "Organize and manage your files more effectively with our enhanced file management tools.",
      },
      {
        id: 32,
        label: "Hot Update",
        title: "Improved Search Algorithm",
        subTitle: "Better Search Results",
        readTime: "Read time: 4 Minutes",
        description: "Experience better and more accurate search results with our improved search algorithm.",
      },
      {
        id: 33,
        label: "New Arrival",
        title: "Mobile App",
        subTitle: "Access Anywhere, Anytime",
        readTime: "Read time: 8 Minutes",
        description: "Stay connected and access your data on the go with our new mobile app.",
      },
      {
        id: 34,
        label: "Feature Highlight",
        title: "Data Backup",
        subTitle: "Protect Your Data",
        readTime: "Read time: 5 Minutes",
        description: "Automatically backup your data to prevent data loss and ensure data security.",
      },
      {
        id: 35,
        label: "What's New",
        title: "Advanced Reporting Tools",
        subTitle: "Detailed Reports",
        readTime: "Read time: 7 Minutes",
        description: "Generate detailed and insightful reports with our advanced reporting tools.",
      },
      {
        id: 36,
        label: "Latest Enhancement",
        title: "Improved User Experience",
        subTitle: "User-Friendly Interface",
        readTime: "Read time: 6 Minutes",
        description: "Enhance your overall user experience with our new and improved user-friendly interface.",
      },
  ];
  
  
  
  export default cardData;
  